const express = require('express')
const router = express.Router()
const User = require('../models/User')
const bcrypt = require('bcryptjs')
const jwt = require('jsonwebtoken')
const {registerUser , loginUser , changePassword , deleteAccount ,fetchDocument} = require('../controllers/userController')
const asyncHandler = require('../middleware/asyncHandler')
const authMiddleware = require('../middleware/auth')
const {forgetPassword , resetPassword , checkTokenValidity} = require('../controllers/passwordResetController')

router.get('/resetpassword' , asyncHandler(checkTokenValidity))
router.post('/forget-password' , asyncHandler(forgetPassword))
router.post('/resetpassword' , asyncHandler(resetPassword))
router.get ('/account' , authMiddleware , asyncHandler(fetchDocument))
router.delete ('/account' , authMiddleware , asyncHandler(deleteAccount))
router.post ('/password' , authMiddleware , asyncHandler(changePassword))
router.post ('/register' , asyncHandler(registerUser))
router.post ('/login' , asyncHandler(loginUser))
module.exports = router